### ISSUE TITLE
Can't detect sixel support in yaft

### ISSUE THREAD

**Issue by hun10** [hackerb9/lsix#25]
yaft is a framebuffer terminal with sixel support: https://github.com/uobikiemukot/yaft

"convert  foo.jpg  -geometry 800x480  sixel:-" does work in yaft.

But lsix says "Error: Your terminal does not report having sixel graphics support."

**Comment by hackerb9** [comment]
Thanks. Sounds like a bug in yaft. I'll let them know.

**Comment by hackerb9** [comment]
Turns out the author of yaft thinks of it as a VT102 that just happens to also do sixel. Since the features needed to detect sixel support didn't exist until the the VT220, there's no way around it other than to simply check if TERM == yaft*. I've added that into the current version of `lsix`. Please try it again and let me know if it works.

By the way, thanks for reporting this bug. I actually hadn't known about yaft before and it seems pretty nifty.

**Comment by hun10** [comment]
Thanks, this works for me.
